-- Table: product_reviews
-- Purpose: Stores product reviews (system-generated by admin, user-generated by customers)

CREATE TABLE IF NOT EXISTS product_reviews (
    id TEXT PRIMARY KEY DEFAULT generate_ulid('prev'),

    -- Product reference
    product_id TEXT NOT NULL REFERENCES products(id),

    -- Review type: 'system' (admin-created) or 'user' (customer-submitted)
    type VARCHAR(10) NOT NULL CHECK (type IN ('system', 'user')),

    -- User references (required for user reviews, NULL for system)
    user_id TEXT REFERENCES users(id),
    order_id TEXT,

    -- Customer display info
    customer_name VARCHAR(100) NOT NULL,
    customer_image_path TEXT,

    -- Review content
    title VARCHAR(200) NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    description TEXT NOT NULL,

    -- Dates
    order_date DATE,
    review_date DATE NOT NULL,

    -- Media (array of {id, type, path, alt_text})
    media JSONB DEFAULT '[]',

    -- Metadata (flexible key-value storage)
    metadata JSONB DEFAULT '{}',

    -- Status and approval
    status BOOLEAN NOT NULL DEFAULT TRUE,
    approval_status VARCHAR(10) NOT NULL DEFAULT 'approved' CHECK (approval_status IN ('approved', 'pending', 'rejected')),

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_product_reviews_product_id ON product_reviews(product_id);
CREATE INDEX idx_product_reviews_type ON product_reviews(type);
CREATE INDEX idx_product_reviews_approval_status ON product_reviews(approval_status);
CREATE INDEX idx_product_reviews_status_approval ON product_reviews(status, approval_status)
    WHERE status = TRUE AND approval_status = 'approved';

-- Trigger: Auto-update updated_at
CREATE TRIGGER set_updated_at_product_reviews
    BEFORE UPDATE ON product_reviews
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
