// Email service
export { sendEmail } from './email.service'
export type { SendEmailOptions, Attachment } from './email.service'

// Templates
export { forgotPasswordTemplate } from './templates/auth/forgot-password.template'
export { orderReceivedCustomerTemplate } from './templates/order/order-received-customer.template'
export { orderReceivedAdminTemplate } from './templates/order/order-received-admin.template'
export { orderConfirmedCustomerTemplate } from './templates/order/order-confirmed-customer.template'
export { orderRejectedCustomerTemplate } from './templates/order/order-rejected-customer.template'
export { cancelApprovedCustomerTemplate } from './templates/order/cancel-approved-customer.template'
export { refundCompletedCustomerTemplate } from './templates/order/refund-completed-customer.template'
export { cancelRejectedCustomerTemplate } from './templates/order/cancel-rejected-customer.template'
export { cancelRequestCustomerTemplate } from './templates/order/cancel-request-customer.template'
export { cancelRequestAdminTemplate } from './templates/order/cancel-request-admin.template'
export { orderShippedCustomerTemplate } from './templates/order/order-shipped-customer.template'
export { orderDeliveredCustomerTemplate } from './templates/order/order-delivered-customer.template'
export { returnRequestCustomerTemplate } from './templates/order/return-request-customer.template'
export { returnRequestAdminTemplate } from './templates/order/return-request-admin.template'
export { returnAcceptedCustomerTemplate } from './templates/order/return-accepted-customer.template'
export { returnRejectedCustomerTemplate } from './templates/order/return-rejected-customer.template'
export { returnPickupScheduledCustomerTemplate } from './templates/order/return-pickup-scheduled-customer.template'
export { returnInTransitCustomerTemplate } from './templates/order/return-in-transit-customer.template'
export { returnReceivedCustomerTemplate } from './templates/order/return-received-customer.template'
export { qcCheckCustomerTemplate } from './templates/order/qc-check-customer.template'
export { qcAcceptedCustomerTemplate } from './templates/order/qc-accepted-customer.template'
export { qcRejectedCustomerTemplate } from './templates/order/qc-rejected-customer.template'
